INSERT INTO utilisateur (nom_user, mot_de_passe, email, type_utilisateur, etat_utilisateur)
VALUES
    ('Jean_Dupont', 'JdP@ss123', 'jean.dupont@example.com', 'p', 'A'),
    ('Marie_Curie', 'McP@ss456', 'marie.curie@example.com', 'p', 'A'),
    ('Albert_Einstein', 'AeP@ss789', 'albert.einstein@example.com', 'p', 'A'),
    ('Isaac_Newton', 'InP@ss101', 'isaac.newton@example.com', 'p', 'A'),
    ('Leonard_DaVinci', 'LdP@ss102', 'leonard.davinci@example.com', 'p', 'A'),
    ('Nikola_Tesla', 'NtP@ss103', 'nikola.tesla@example.com', 'p', 'A'),
    ('Galileo_Galilei', 'GgP@ss104', 'galileo.galilei@example.com', 'p', 'A'),
    ('Ada_Lovelace', 'AlP@ss105', 'ada.lovelace@example.com', 'p', 'A'),
    ('Alan_Turing', 'AtP@ss106', 'alan.turing@example.com', 'p', 'A'),
    ('Richard_Feynman', 'RfP@ss107', 'richard.feynman@example.com', 'p', 'A'),
    ('Carl_Sagan', 'CsP@ss108', 'carl.sagan@example.com', 'p', 'A'),
    ('Stephen_Hawking', 'ShP@ss109', 'stephen.hawking@example.com', 'p', 'A'),
    ('Rosalind_Franklin', 'RfP@ss110', 'rosalind.franklin@example.com', 'p', 'A'),
    ('Katherine_Johnson', 'KjP@ss111', 'katherine.johnson@example.com', 'p', 'A'),
    ('Dmitri_Mendeleev', 'DmP@ss112', 'dmitri.mendeleev@example.com', 'p', 'A'),
    ('Niels_Bohr', 'NbP@ss113', 'niels.bohr@example.com', 'p', 'A'),
    ('Max_Planck', 'MpP@ss114', 'max.planck@example.com', 'p', 'A'),
    ('Emmy_Noether', 'EnP@ss115', 'emmy.noether@example.com', 'p', 'A'),
    ('Barbara_McClintock', 'BmP@ss116', 'barbara.mcclintock@example.com', 'p', 'A'),
    ('Dorothy_Hodgkin', 'DhP@ss117', 'dorothy.hodgkin@example.com', 'p', 'A'),
    ('Subrahmanyan_Chandrasekhar', 'ScP@ss118', 'subrahmanyan.chandrasekhar@example.com', 'p', 'A'),
    ('Michael_Faraday', 'MfP@ss119', 'michael.faraday@example.com', 'p', 'A'),
    ('James_Maxwell', 'JmP@ss120', 'james.maxwell@example.com', 'p', 'A'),
    ('Erwin_Schrodinger', 'EsP@ss121', 'erwin.schrodinger@example.com', 'p', 'A'),
    ('Richard_Dawkins', 'RdP@ss122', 'richard.dawkins@example.com', 'p', 'A'),
    ('Alice_Martin', 'AmE@ss201', 'alice.martin@example.com', 'e', 'A'),
    ('Bob_Lemoine', 'BlE@ss202', 'bob.lemoine@example.com', 'e', 'A'),
    ('Charlie_Dupuis', 'CdE@ss203', 'charlie.dupuis@example.com', 'e', 'A'),
    ('David_Bernard', 'DbE@ss204', 'david.bernard@example.com', 'e', 'A'),
    ('Emma_Leclerc', 'ElE@ss205', 'emma.leclerc@example.com', 'e', 'A'),
    ('Felix_Roux', 'FrE@ss206', 'felix.roux@example.com', 'e', 'A'),
    ('Gabrielle_Andre', 'GaE@ss207', 'gabrielle.andre@example.com', 'e', 'A'),
    ('Hugo_Morel', 'HmE@ss208', 'hugo.morel@example.com', 'e', 'A'),
    ('Isabelle_Fournier', 'IfE@ss209', 'isabelle.fournier@example.com', 'e', 'A'),
    ('Julien_Guillot', 'JgE@ss210', 'julien.guillot@example.com', 'e', 'A'),
    ('Karine_Durand', 'KdE@ss211', 'karine.durand@example.com', 'e', 'A'),
    ('Luc_Mercier', 'LmE@ss212', 'luc.mercier@example.com', 'e', 'A'),
    ('Manon_Germain', 'MgE@ss213', 'manon.germain@example.com', 'e', 'A'),
    ('Nicolas_Delahaye', 'NdE@ss214', 'nicolas.delahaye@example.com', 'e', 'A'),
    ('Olivier_Lemoine', 'OlE@ss215', 'olivier.lemoine@example.com', 'e', 'A'),
    ('Pauline_Denis', 'PdE@ss216', 'pauline.denis@example.com', 'e', 'A'),
    ('Quentin_Gosselin', 'QgE@ss217', 'quentin.gosselin@example.com', 'e', 'A'),
    ('Raphael_Caron', 'RcE@ss218', 'raphael.caron@example.com', 'e', 'A'),
    ('Sophie_Morel', 'SmE@ss219', 'sophie.morel@example.com', 'e', 'A'),
    ('Thomas_Benoit', 'TbE@ss220', 'thomas.benoit@example.com', 'e', 'A'),
    ('Ursula_Perrot', 'UpE@ss221', 'ursula.perrot@example.com', 'e', 'A'),
    ('Victor_Aubert', 'VaE@ss222', 'victor.aubert@example.com', 'e', 'A'),
    ('William_Lucas', 'WlE@ss223', 'william.lucas@example.com', 'e', 'A'),
    ('Xavier_Guichard', 'XgE@ss224', 'xavier.guichard@example.com', 'e', 'A');


INSERT INTO etudiant (equipe_id_equipe, nom_complet, etat_etudiant, utilisateur_id_user)
VALUES
    (3, 'Alice Martin', 'A', 26),
    (7, 'Bob Lemoine', 'A', 27),
    (2, 'Charlie Dupuis', 'A', 28),
    (8, 'David Bernard', 'A', 29),
    (5, 'Emma Leclerc', 'A', 30),
    (1, 'Felix Roux', 'A', 31),
    (9, 'Gabrielle Andre', 'A', 32),
    (6, 'Hugo Morel', 'A', 33),
    (4, 'Isabelle Fournier', 'A', 34),
    (10, 'Julien Guillot', 'A', 35),
    (3, 'Karine Durand', 'A', 36),
    (7, 'Luc Mercier', 'A', 37),
    (2, 'Manon Germain', 'A', 38),
    (8, 'Nicolas Delahaye', 'A', 39),
    (5, 'Olivier Lemoine', 'A', 40),
    (1, 'Pauline Denis', 'A', 41),
    (9, 'Quentin Gosselin', 'A', 42),
    (6, 'Raphael Caron', 'A', 43),
    (4, 'Sophie Morel', 'A', 44),
    (10, 'Thomas Benoit', 'A', 45),
    (3, 'Ursula Perrot', 'A', 46),
    (7, 'Victor Aubert', 'A', 47),
    (2, 'William Lucas', 'A', 48),
    (8, 'Xavier Guichard', 'A', 49);

INSERT INTO professeur (nom_complet, etat_professeur, utilisateur_id_user) VALUES
    ('Jean Dupont', 'A', 1),
    ('Marie Curie', 'A', 2),
    ('Albert Einstein', 'A', 3),
    ('Isaac Newton', 'A', 4),
    ('Leonard Da Vinci', 'A', 5),
    ('Nikola Tesla', 'A', 6),
    ('Galileo Galilei', 'A', 7),
    ('Ada Lovelace', 'A', 8),
    ('Alan Turing', 'A', 9),
    ('Richard Feynman', 'A', 10),
    ('Carl Sagan', 'A', 11),
    ('Stephen Hawking', 'A', 12),
    ('Rosalind Franklin', 'A', 13),
    ('Katherine Johnson', 'A', 14),
    ('Dmitri Mendeleev', 'A', 15),
    ('Niels Bohr', 'A', 16),
    ('Max Planck', 'A', 17),
    ('Emmy Noether', 'A', 18),
    ('Barbara McClintock', 'A', 19),
    ('Dorothy Hodgkin', 'A', 20),
    ('Subrahmanyan Chandrasekhar', 'A', 21),
    ('Michael Faraday', 'A', 22),
    ('James Maxwell', 'A', 23),
    ('Erwin Schrodinger', 'A', 24),
    ('Richard Dawkins', 'A', 25);


INSERT INTO Cours (code_cours, description_cours, etat_cours, session_id_session) VALUES
('CS101', 'Introduction aux concepts fondamentaux de l informatique, y compris la programmation de base et les algorithmes.', 1, 1),
('MATH200', 'Cours de mathematiques avancees abordant les equations differentielles, les series et l analyse complexe.', 1, 1),
('BIO150', 'Exploration des concepts de base de la biologie, y compris la cellule, la genetique, et les bases de l evolution.', 1, 1),
('PHYS250', 'Introduction a la physique, avec un accent particulier sur la mecanique et l electromagnetisme.', 1, 2),
('CHEM200', 'Chimie generale, avec une etude des elements, des reactions chimiques, et des concepts de la thermodynamique.', 1, 2),
('ECON210', 'Introduction a l economie, avec des sujets tels que l offre et la demande, la microeconomie et la macroeconomie.', 1, 3),
('ENGR300', 'Principes de la mecanique appliquee, couvrant la statique, la dynamique et l analyse des structures.', 1, 3),
('HIST101', 'Cours d histoire generale, abordant les grandes periodes historiques de l Antiquite a la Renaissance.', 1, 4),
('MATH300', 'Calcul differentiel avance, axe sur l integration multivariable et les theoremes associes.', 1, 4),
('PSY101', 'Introduction a la psychologie, incluant les bases des comportements humains, des emotions et des processus cognitifs.', 1, 5),
('CS202', 'Structures de donnees avancees, telles que les listes, les piles, les files, et les arbres binaires.', 1, 5),
('MATH400', 'Introduction aux equations differentielles et leur application dans les sciences naturelles et l ingenierie.', 0, 6),
('CHEM300', 'Chimie organique, incluant les reactions chimiques des molecules organiques et les mecanismes reactionnels.', 1, 6),
('BIO200', 'Genetique et biologie moleculaire, avec une etude approfondie de l ADN, de la replication et de la mutation genetique.', 1, 7),
('PHYS300', 'Physique moderne, centree sur la relativite restreinte, la mecanique quantique et les applications pratiques.', 0, 7),
('ECON310', 'Theorie economique appliquee, couvrant les modeles de croissance economique et les politiques monetaire et fiscales.', 1, 8),
('ENGR350', 'Mecanique des fluides, incluant les principes de base des fluides en mouvement et au repos, et leur application dans les systemes industriels.', 1, 8),
('MATH500', 'Algebre abstraite, abordant les groupes, les anneaux, les corps, et leur application dans les systemes mathematiques complexes.', 0, 9),
('CS303', 'Conception d algorithmes et analyse de la complexite, incluant les algorithmes de tri, de recherche, et les structures de donnees complexes.', 1, 9),
('ART100', 'Introduction a l art, incluant l histoire des mouvements artistiques et l etude des techniques artistiques a travers le temps.', 1, 10),
('ENGR400', 'Cours de thermodynamique, centree sur les lois de la thermodynamique et leur application aux systemes physiques et chimiques.', 1, 10),
('PHIL101', 'Introduction a la philosophie, incluant les principales ecoles de pensee, l ethique, et la logique fondamentale.', 1, 11),
('SOC101', 'Introduction a la sociologie, abordant les structures sociales, la culture, et le role des institutions dans la societe.', 1, 11),
('MATH600', 'Analyse complexe, incluant les fonctions analytiques, les integrales complexes et les series de Laurent.', 0, 12),
('CS404', 'Introduction aux systemes d exploitation, incluant la gestion de la memoire, des processus et des systemes de fichiers.', 1, 12),
('LING101', 'Introduction a la linguistique, etudiant les sons, la syntaxe, et l evolution des langues humaines.', 1, 13);

